CREATE TABLE Planos (
    ID INT PRIMARY KEY,
    Nome NVARCHAR(50) NOT NULL
);

INSERT INTO Planos (ID, Nome) VALUES
(0, 'Gold'),
(1, 'Silver');



CREATE TABLE SaudeBoi (
    ID INT PRIMARY KEY,
    Descricao NVARCHAR(50) NOT NULL
);

INSERT INTO SaudeBoi (ID, Descricao) VALUES
(0, 'Saudavel'),
(1, 'Atenção'),
(2, 'CuidadosMedicos');



CREATE TABLE T_AGROCARE_VETERINARIO (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(2000) NOT NULL,
    NumCrmv NVARCHAR(2000) NOT NULL,
    Especialidade NVARCHAR(2000) NOT NULL,
    Telefone BIGINT NOT NULL,
    Email NVARCHAR(2000) NOT NULL,
    Password NVARCHAR(2000) NOT NULL
);



CREATE TABLE T_AGROCARE_AGROPECUARISTA (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(2000) NOT NULL,
    Number BIGINT NOT NULL,
    Endereco NVARCHAR(2000) NOT NULL,
    NumerosAnimais INT NOT NULL,
    Email NVARCHAR(2000) NOT NULL,
    Password NVARCHAR(2000) NOT NULL,
    Status BIT NOT NULL,
    Planos INT NOT NULL
);




CREATE TABLE T_AGROCARE_BOVINO (
    Id BIGINT PRIMARY KEY,
    Saude FLOAT NOT NULL,
    UltimoDiaAtualizacao DATETIME NOT NULL,
    SaudeBoiID INT NOT NULL,
    UserID BIGINT NOT NULL,
    ConsultaID BIGINT NULL
);



ALTER TABLE T_AGROCARE_BOVINO
ADD CONSTRAINT FK_Boi_User FOREIGN KEY (UserID) REFERENCES T_AGROCARE_AGROPECUARISTA(ID),
    CONSTRAINT FK_Boi_SaudeBoi FOREIGN KEY (SaudeBoiID) REFERENCES SaudeBoi(ID);




CREATE TABLE T_AGROCARE_CONSULTAS (
    ID BIGINT PRIMARY KEY,
    Descricao NVARCHAR(255) NOT NULL,
    Observacao NVARCHAR(255) NOT NULL,
    DataConsulta DATETIME NOT NULL,
    IdBoi BIGINT NOT NULL,
    IdUser BIGINT NOT NULL,
    IdVeterinario BIGINT NOT NULL,
    CONSTRAINT FK_Consulta_Boi FOREIGN KEY (IdBoi) REFERENCES T_AGROCARE_BOVINO(Id),
    CONSTRAINT FK_Consulta_User FOREIGN KEY (IdUser) REFERENCES T_AGROCARE_AGROPECUARISTA(ID),
    CONSTRAINT FK_Consulta_Veterinario FOREIGN KEY (IdVeterinario) REFERENCES T_AGROCARE_VETERINARIO(Id)
);


ALTER TABLE T_AGROCARE_BOVINO
ADD CONSTRAINT FK_Boi_Consulta FOREIGN KEY (ConsultaID) REFERENCES T_AGROCARE_CONSULTAS(ID);



CREATE TABLE T_AGROCARE_AVALIACOES (
    IdAvaliacoes BIGINT PRIMARY KEY,
    QtdEstrelas INT CHECK (QtdEstrelas BETWEEN 1 AND 5),
    MsgAvaliacao NVARCHAR(255),
    DataAvaliacao DATETIME,
    ConsultaID BIGINT NOT NULL,
    VeterinarioID BIGINT NOT NULL,
    UserID BIGINT NOT NULL,
    CONSTRAINT FK_Avaliacao_Consulta FOREIGN KEY (ConsultaID) REFERENCES T_AGROCARE_CONSULTAS(ID),
    CONSTRAINT FK_Avaliacao_Veterinario FOREIGN KEY (VeterinarioID) REFERENCES T_AGROCARE_VETERINARIO(Id),
    CONSTRAINT FK_Avaliacao_User FOREIGN KEY (UserID) REFERENCES T_AGROCARE_AGROPECUARISTA(ID)
);



CREATE TABLE T_AGROCARE_TRATAMENTO (
    IdTratamento BIGINT PRIMARY KEY,
    TipoTratamento NVARCHAR(100),
    NomeMedicamento NVARCHAR(100),
    DoseMedicamentoML DECIMAL(10, 2),
    DescricaoTratamento NVARCHAR(255),
    ViaAdministracao NVARCHAR(100),
    DuracaoTratamento INT,
    EfeitoTratamento NVARCHAR(255),
    ObservacaoTratamento NVARCHAR(255),
    DataTratamento DATETIME,
    VeterinarioID BIGINT NOT NULL,
    ConsultaID BIGINT NOT NULL,
    Idboi BIGINT NOT NULL,
    UserID BIGINT NOT NULL,
    CONSTRAINT FK_Tratamento_Veterinario FOREIGN KEY (VeterinarioID) REFERENCES T_AGROCARE_VETERINARIO(Id),
    CONSTRAINT FK_Tratamento_Consulta FOREIGN KEY (ConsultaID) REFERENCES T_AGROCARE_CONSULTAS(ID),
    CONSTRAINT FK_Tratamento_Boi FOREIGN KEY (Idboi) REFERENCES T_AGROCARE_BOVINO(Id),
    CONSTRAINT FK_Tratamento_User FOREIGN KEY (UserID) REFERENCES T_AGROCARE_AGROPECUARISTA(ID)
);



